language: ruby
rvm:
# for 2.2 support we need to upgrade the pg gem
  - 2.1.6

sudo: false
addons:
  apt:
    packages:
      - po4a
      - iso-codes
      - tango-icon-theme
      - pidgin-data
      # for gem extensions
      - libmagickwand-dev
      - libpq-dev
      - libreadline-dev
      - libsqlite3-dev
      - libxslt1-dev

before_install:
  - export PARALLEL_TESTS=1
# workaround for https://github.com/travis-ci/travis-ci/issues/4536
  - export GEM_HOME=$PWD/vendor/bundle/ruby/2.1.0
  - gem install bundler
cache: bundler

before_script:
  - mkdir -p tmp/pids log
# workaround for plugins with Gemfile
  - perl -pi -e 's/cat .+ > \$gemfile/echo "source \\"https:\/\/rubygems.org\\"" > \$gemfile && cat \$source\/Gemfile >> \$gemfile/' script/noosfero-plugins
  - perl -pi -e 's/--local --quiet/install --jobs=3 --retry=3/' script/noosfero-plugins
  - script/noosfero-plugins disableall
  - bundle exec rake makemo &>/dev/null
# database
  - cp config/database.yml.travis config/database.yml
  - export PARALLEL_TEST_PROCESSORS=3
  - psql -c 'create database test;' -U postgres
  - psql -c 'create database test2;' -U postgres
  - psql -c 'create database test3;' -U postgres
  - TEST_ENV_NUMBER='' bundle exec rake db:schema:load &>/dev/null
  - TEST_ENV_NUMBER=2 bundle exec rake db:schema:load &>/dev/null
  - TEST_ENV_NUMBER=3 bundle exec rake db:schema:load &>/dev/null
  #- rake parallel:create
  - rake parallel:prepare[$PARALLEL_TEST_PROCESSORS]

env:
  - TASK=test:units
  - TASK=test:functionals
  - TASK=test:integration
  - TASK=cucumber
  - TASK=selenium
  - TASK=test:noosfero_plugins

script:
  - bundle exec rake parallel:rake[$TASK]

